const content = {
  filterItems: [
    {
      id: Math.round(Math.random() * 99999),
      name: 'All',
    },
    {
      id: Math.round(Math.random() * 99999),
      name: 'Flowers',
    },
    {
      id: Math.round(Math.random() * 99999),
      name: 'Pots',
    },
    {
      id: Math.round(Math.random() * 99999),
      name: 'Plants',
    },
    {
      id: Math.round(Math.random() * 99999),
      name: 'Cactus',
    },
  ],
  shopItems: [
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(1).jpg',
      name: 'Flower 1',
      price: 23.99,
      categories: ['flower', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(2).jpg',
      name: 'Flower 2',
      price: 21.99,
      categories: ['plant', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(3).jpg',
      name: 'Flower 3',
      price: 24.99,
      categories: ['plant', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(4).jpg',
      name: 'Flower 4',
      price: 29.99,
      categories: ['pot', 'cactus'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(5).jpg',
      name: 'Flower 5',
      price: 24.99,
      categories: ['flowers'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(6).jpg',
      name: 'Flower 6',
      price: 19.99,
      categories: ['flowers'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(7).jpg',
      name: 'Flower 7',
      price: 22.99,
      categories: ['flowers'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(8).jpg',
      name: 'Flower 8',
      price: 27.99,
      categories: ['plant', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(9).jpg',
      name: 'Flower 9',
      price: 29.99,
      categories: ['flowers'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(10).jpg',
      name: 'Flower 10',
      price: 20.99,
      categories: ['flowers'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(11).jpg',
      name: 'Flower 11',
      price: 24.99,
      categories: ['flowers', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(12).jpg',
      name: 'Flower 12',
      price: 22.99,
      categories: ['cactus', 'plant', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(13).jpg',
      name: 'Flower 13',
      price: 23.99,
      categories: ['plant', 'pot', 'cactus'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(14).jpg',
      name: 'Flower 14',
      price: 24.99,
      categories: ['cactus', 'cactus'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(15).jpg',
      name: 'Flower 15',
      price: 25.99,
      categories: ['plant', 'pot'],
    },
    {
      id: Math.round(Math.random() * 99999),
      img: 'https://raw.githubusercontent.com/Luciana-Santos/floral-fantasy/master/public/assets/shop_item-img%20(16).jpg',
      name: 'Flower 16',
      price: 26.99,
      categories: ['plant', 'pot'],
    },
  ],
};

export default content;
